controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    maci_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    maci_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    use_sim_time: True

maci_joint_state_broadcaster:
  ros__parameters:
    use_sim_time: True

maci_controller:
  ros__parameters:
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    hold_on: true
    joints:
      - finger_joint
      - left_inner_finger_joint
      - right_outer_knuckle_joint
      - right_inner_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
# In order for the multi-robot setup to work, we need to load all the params in the robot
# that loads first. Thus we are going to keep krytn's control parameters here too.
krytn:
  controller_manager:
    ros__parameters:
      update_rate: 100 # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diff_drive_base_controller:
        type: diff_drive_controller/DiffDriveController

  diff_drive_base_controller:
    ros__parameters:
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]

      wheel_separation: 0.326
      wheels_per_side: 2
      wheel_radius: 0.128

      wheel_separation_multiplier: 1.0
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      publish_rate: 50.0
      odom_frame_id: odom
      base_frame_id: base_footprint
      #pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.11]
      #twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

      open_loop: false
      enable_odom_tf: true

      cmd_vel_timeout: 0.5
      #publish_limited_velocity: true
      use_stamped_vel: false
      #velocity_rolling_window_size: 10

      # Velocity and acceleration limits
      # Whenever a min_* is unspecified, default to -max_*
      linear.x.has_velocity_limits: true
      linear.x.has_acceleration_limits: true
      linear.x.has_jerk_limits: false
      linear.x.max_velocity: 1.0
      linear.x.min_velocity: -1.0
      linear.x.max_acceleration: 1.0
      linear.x.max_jerk: 0.0
      linear.x.min_jerk: 0.0

      angular.z.has_velocity_limits: true
      angular.z.has_acceleration_limits: true
      angular.z.has_jerk_limits: false
      angular.z.max_velocity: 1.0
      angular.z.min_velocity: -1.0
      angular.z.max_acceleration: 1.0
      angular.z.min_acceleration: -1.0
      angular.z.max_jerk: 0.0
      angular.z.min_jerk: 0.0
